server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Si la ruta no existe físicamente, redirige a Angular para que él la maneje
        try_files $uri $uri/ /index.html;
    }
}